#!/bin/bash

CSCOPE_DIR="$PWD/.cscope"

if ! [ -x "$(command -v cscope)" ]; then
    echo "Installing cscope..." >&2
    sudo apt install -y cscope;
fi

if [ ! -d "$CSCOPE_DIR" ]; then
mkdir "$CSCOPE_DIR"
fi

echo "Finding files ..."
find "$PWD" -name '*.[ch]' \
-o -name '*.go' \
-o -name '*.java' \
-o -name '*properties' \
-o -name '*.cpp' \
-o -name '*.cc' \
-o -name '*.hpp' \
-o -name '*.py' \
-o -name '*.php' > "$CSCOPE_DIR/cscope.files"

echo "Adding files to cscope db: $PWD/cscope.db ..."
pushd $CSCOPE_DIR
cscope -b
popd
#cscope -b -i "$CSCOPE_DIR/cscope.files"


export CSCOPE_DB="$CSCOPE_DIR/cscope.out"
#CSCOPE_DB=$PWD/cscope.out
#export CSCOPE_DB
echo "Exported CSCOPE_DB to: '$CSCOPE_DB'"


# Generate tags
if ! [ -x "$(command -v ctags)" ]; then
    echo "Installing ctags..." >&2
    sudo apt install -y exuberant-ctags;
fi
ctags -R .
