#!/bin/bash

# Set default shell to zsh
# chsh -s $(`which zsh`) $USER

# Using Tmux as default when start bash
#[[ "$TMUX" = "" ]] && tmux

alias root='sudo -s'
alias sophal='su - sophal'
alias sb='source ~/.zshrc'
alias q='exit'

alias generate_ctags='source ~/.myEnv/others/gentags_cscope'

alias ssh_101='ssh -o TCPKeepAlive=yes -o ServerAliveInterval=360 root@192.168.0.101' #pw: root
alias ssh_102='ssh -o TCPKeepAlive=yes -o ServerAliveInterval=360 root@192.168.0.102' #pw: root
alias ssh_103='ssh -o TCPKeepAlive=yes -o ServerAliveInterval=360 root@192.168.0.103' #pw: root
alias ssh_tos='ssh -o TCPKeepAlive=yes -o ServerAliveInterval=360 root@192.168.0.105' #pw: root
